version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped